server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiples-instancias
          uri: https://github.com/jlcudris/microservicios-spring-boot-eureka-y-demas
          search-paths: config-data
  application:
    name: config-service
